# name: C/C++ CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: make
#       run: cmake -B build -S .
#     - name: make check
#       run: cmake --build build

name: Build C++ Project in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Docker on Self-hosted Runner
    runs-on: self-hosted

    steps:
      - name: Set up unique work directory
        run: |
          export WORK_DIR="${PWD}/actions-runner/_work/$(date +%Y%m%d%H%M%S)"
          echo "WORK_DIR=${WORK_DIR}" >> $GITHUB_ENV
          echo ${WORK_DIR}
          mkdir -p ${WORK_DIR}
      - name: Clean build directory
        run: | 
          rm -rf ${WORK_DIR}/* 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build inside Docker and output artifact
        run: |
          docker run --rm \
            -v "${WORK_DIR}:/workspace" \
            -v "${PWD}/build:/output" \
            --entrypoint bash davidwu-base-gcc:1.0  -c "
              cd /workspace &&
              mkdir -p build &&
              cd build &&
              cmake .. &&
              make &&
              chmod -R 777 ./* &&
              echo done"
      - name: Clean up work directory
        run: |
          rm -rf ${WORK_DIR}  # 清理工作目录