# name: C/C++ CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: make
#       run: cmake -B build -S .
#     - name: make check
#       run: cmake --build build

name: Build C++ Project in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Docker on Self-hosted Runner
    runs-on: self-hosted

    steps:
      - name: Clean build directory
        run: | 
          rm -rf ${PWD}/actions-runner/_work/*
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build inside Docker and output artifact
        run: |
          docker run --rm \
            -v "${PWD}:/workspace" \
            -v "${PWD}/build:/output" \
            --entrypoint bash davidwu-base-gcc:1.0  -c "cd /workspace &&
              mkdir -p build &&
              cd build &&
              cmake .. &&
              make &&
              chmod -R 777 ./* &&
              rm -rf ../build/actions-runner/_work/* &&
              ls ../build/actions-runner/_work/ &&
              echo done" 